#!/bin/bash

#Programme pour vérifier si un hote est joignable ou pas

reply=$(ping  -c1 $1 | grep -o "ttl")

#on vérifie si il y a des ttl (paquet qui revienne) dans la réponse du ping

if test "$reply" = "ttl";then
	echo "joignable"
else 
	echo "injoignable"
fi

