#!/bin/bash

while [ "$correct" != "oui" ]
do
	echo -n "Entrez le nom du "site" :"
	read site
	echo -n "Vous avez choisi $site, es-ce correct?(oui/non): "
	read correct
		if [ "$correct" = "oui" ] ; then
	
	echo "Vous avez bien choisi" $site
	
	elif [ "$correct" = "non" ] ; then
	echo "Veuillez recommencer"

fi
done

