#!/bin/bash
pingmax=200
#ping max est notre variable max
Rping=150.5
#Rping à définir par rapport au résultat du ping toutes les 5 mins
declare -i Fructueux=0
declare -i Infructueux=0
if [ $(echo "$Rping > $pingmax" | bc -l) -eq 1 ]
then	Infructueux=$Infructueux+1
	echo "Temps de réponse supérieur à 200ms"
else	Fructueux=$Fructueux+1
	echo "Temps de réponse satisfaisant"
fi
echo "Le nombre de réponses fructueuses est $Fructueux"
echo "Le nombre de réponses infructueuses est $Infructueux" 
